# Site settings
title: RAIABRIL
email: rai@ingmechs.com
url: https://raiabril.github.io
description: "This is my personal website and portfolio."
keywords: "data,analytics,engineering,iot,connected,smart,business,prototypes,injection,moulds"
skills: "Data Analytics - Innovation - Project Management"
meta_author: Abril Raimundo

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: raiabril

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ededf0 #80B3FF
  primary-rgb: "237,237,240" #"128,179,255"
  secondary: 	27293a #FD6E8A
  secondary-dark: 27293a #A2122F

# Footer settings
footer:
  copyright: Raimundo Abril 2017
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/raiskv
  - title: linkedin
    url: https://www.linkedin.com/in/raimundo-abril-l%C3%B3pez-a700143a/
  - title: github
    url: http://github.com/raiabril

# Postal address (add as many lines as necessary)
address:
  - line: Business Incubator Puente de Vallecas
  - line: 9 Calle la Diligencia
  - line: ES 28018 Madrid

# Credits content
credits:
  - line: 'Startbootstrap and Github'
  - line: 'Medialab Prado Madrid'
  - line: 'Ayuntamiento de Madrid'
  - line: 'Universidad Politécnica de Madrid'
  - line: 'Universidad Rey Juan Carlos'

# Build settings
markdown: kramdown
permalink: pretty
